name: GitHub-Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: googleknight
          template: classic
          base: header, repositories
          config_timezone: Asia/Kolkata

          # Output settings
          output_action: commit
          committer_branch: output
          filename: github-metrics.svg

          # Plugins
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          # Styling
          config_order: base.header, base.repositories, languages
